apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-v01-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-v01
  template:
    metadata:
      labels:
        app: project-v01
    spec:
      containers:
        - name: project-v01
          image: draganculibrk9/project-v01:latest
          env:
          - name: PORT
            value: "3000"