apiVersion: v1
kind: PersistentVolume
metadata:
  name: exercise-1.11-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - k3d-k3s-default-agent-0